//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteMarCore.ProceduresAndViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIM_PERSONAS
    {
        public int id_gentemar { get; set; }
        public int id_usuario { get; set; }
        public string foto { get; set; }
        public string huella { get; set; }
        public string firma { get; set; }
        public string firma_bin { get; set; }
        public string firma_formato { get; set; }
        public string fecha_edicion_captura { get; set; }
        public int idDim_impresion { get; set; }
        public int id_origen_huella { get; set; }
    }
}
