//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteMarCore.ProceduresAndViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENTEMAR_CARGO_LICENCIA_NAVES
    {
        public long id_licencia_nave { get; set; }
        public int id_cargo_licencia { get; set; }
        public string identi { get; set; }
    }
}
