//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteMarCore.ProceduresAndViews
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_nav_med
    {
        public string identi { get; set; }
        public Nullable<decimal> eslora { get; set; }
        public Nullable<decimal> manga { get; set; }
        public Nullable<decimal> puntal { get; set; }
        public Nullable<decimal> calado { get; set; }
        public Nullable<decimal> trb { get; set; }
        public Nullable<decimal> trn { get; set; }
        public Nullable<decimal> tpm { get; set; }
        public Nullable<decimal> franco_bordo { get; set; }
        public Nullable<decimal> cod_andino { get; set; }
        public Nullable<decimal> tacarreo { get; set; }
    }
}
